language: r
r: devel
sudo: FALSE
cache: packages

warnings_are_errors: FALSE

r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes'

r_github_packages:
  - hadley/devtools@efa894ffa

language: r

addons:
  apt:
    packages:
      - devscripts
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libudunits2-dev
      - libv8-dev
      - libgsl-dev
      - libgdal-dev
      - libproj-dev
      
env:
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
